/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetAlliancesAllianceIdOk { 
    /**
     * ID of the corporation that created the alliance
     */
    creator_corporation_id: number;
    /**
     * ID of the character that created the alliance
     */
    creator_id: number;
    /**
     * date_founded string
     */
    date_founded: Date;
    /**
     * the executor corporation ID, if this alliance is not closed
     */
    executor_corporation_id?: number;
    /**
     * Faction ID this alliance is fighting for, if this alliance is enlisted in factional warfare
     */
    faction_id?: number;
    /**
     * the full name of the alliance
     */
    name: string;
    /**
     * the short name of the alliance
     */
    ticker: string;
}
