/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdIconsOk { 
    /**
     * px128x128 string
     */
    px128x128?: string;
    /**
     * px256x256 string
     */
    px256x256?: string;
    /**
     * px64x64 string
     */
    px64x64?: string;
}
