/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * social object
 */
export interface GetCharactersCharacterIdStatsSocial { 
    /**
     * add_contact_bad integer
     */
    add_contact_bad?: number;
    /**
     * add_contact_good integer
     */
    add_contact_good?: number;
    /**
     * add_contact_high integer
     */
    add_contact_high?: number;
    /**
     * add_contact_horrible integer
     */
    add_contact_horrible?: number;
    /**
     * add_contact_neutral integer
     */
    add_contact_neutral?: number;
    /**
     * add_note integer
     */
    add_note?: number;
    /**
     * added_as_contact_bad integer
     */
    added_as_contact_bad?: number;
    /**
     * added_as_contact_good integer
     */
    added_as_contact_good?: number;
    /**
     * added_as_contact_high integer
     */
    added_as_contact_high?: number;
    /**
     * added_as_contact_horrible integer
     */
    added_as_contact_horrible?: number;
    /**
     * added_as_contact_neutral integer
     */
    added_as_contact_neutral?: number;
    /**
     * calendar_event_created integer
     */
    calendar_event_created?: number;
    /**
     * chat_messages_alliance integer
     */
    chat_messages_alliance?: number;
    /**
     * chat_messages_constellation integer
     */
    chat_messages_constellation?: number;
    /**
     * chat_messages_corporation integer
     */
    chat_messages_corporation?: number;
    /**
     * chat_messages_fleet integer
     */
    chat_messages_fleet?: number;
    /**
     * chat_messages_region integer
     */
    chat_messages_region?: number;
    /**
     * chat_messages_solarsystem integer
     */
    chat_messages_solarsystem?: number;
    /**
     * chat_messages_warfaction integer
     */
    chat_messages_warfaction?: number;
    /**
     * chat_total_message_length integer
     */
    chat_total_message_length?: number;
    /**
     * direct_trades integer
     */
    direct_trades?: number;
    /**
     * fleet_broadcasts integer
     */
    fleet_broadcasts?: number;
    /**
     * fleet_joins integer
     */
    fleet_joins?: number;
    /**
     * mails_received integer
     */
    mails_received?: number;
    /**
     * mails_sent integer
     */
    mails_sent?: number;
}
