/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Not found
 */
export interface GetCharactersCharacterIdContractsContractIdBidsNotFound { 
    /**
     * Not found message
     */
    error?: string;
}
