/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * wallet transaction
 */
export interface GetCorporationsCorporationIdWalletsDivisionTransactions200Ok { 
    /**
     * client_id integer
     */
    client_id: number;
    /**
     * Date and time of transaction
     */
    date: Date;
    /**
     * is_buy boolean
     */
    is_buy: boolean;
    /**
     * -1 if there is no corresponding wallet journal entry
     */
    journal_ref_id: number;
    /**
     * location_id integer
     */
    location_id: number;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * Unique transaction ID
     */
    transaction_id: number;
    /**
     * type_id integer
     */
    type_id: number;
    /**
     * Amount paid per unit
     */
    unit_price: number;
}
