/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdNotificationsContacts200Ok { 
    /**
     * message string
     */
    message: string;
    /**
     * notification_id integer
     */
    notification_id: number;
    /**
     * send_date string
     */
    send_date: Date;
    /**
     * sender_character_id integer
     */
    sender_character_id: number;
    /**
     * A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
     */
    standing_level: number;
}
