/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdSkillqueue200Ok { 
    /**
     * finish_date string
     */
    finish_date?: Date;
    /**
     * finished_level integer
     */
    finished_level: number;
    /**
     * level_end_sp integer
     */
    level_end_sp?: number;
    /**
     * Amount of SP that was in the skill when it started training it's current level. Used to calculate % of current level complete.
     */
    level_start_sp?: number;
    /**
     * queue_position integer
     */
    queue_position: number;
    /**
     * skill_id integer
     */
    skill_id: number;
    /**
     * start_date string
     */
    start_date?: Date;
    /**
     * training_start_sp integer
     */
    training_start_sp?: number;
}
