/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdPlanetsPlanetIdContent } from './getCharactersCharacterIdPlanetsPlanetIdContent';
import { GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails } from './getCharactersCharacterIdPlanetsPlanetIdExtractorDetails';
import { GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails } from './getCharactersCharacterIdPlanetsPlanetIdFactoryDetails';


/**
 * pin object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdPin { 
    /**
     * contents array
     */
    contents?: Array<GetCharactersCharacterIdPlanetsPlanetIdContent>;
    /**
     * expiry_time string
     */
    expiry_time?: Date;
    extractor_details?: GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails;
    factory_details?: GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails;
    /**
     * install_time string
     */
    install_time?: Date;
    /**
     * last_cycle_start string
     */
    last_cycle_start?: Date;
    /**
     * latitude number
     */
    latitude: number;
    /**
     * longitude number
     */
    longitude: number;
    /**
     * pin_id integer
     */
    pin_id: number;
    /**
     * schematic_id integer
     */
    schematic_id?: number;
    /**
     * type_id integer
     */
    type_id: number;
}
