/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * mining object
 */
export interface GetCharactersCharacterIdStatsMining { 
    /**
     * drone_mine integer
     */
    drone_mine?: number;
    /**
     * ore_arkonor integer
     */
    ore_arkonor?: number;
    /**
     * ore_bistot integer
     */
    ore_bistot?: number;
    /**
     * ore_crokite integer
     */
    ore_crokite?: number;
    /**
     * ore_dark_ochre integer
     */
    ore_dark_ochre?: number;
    /**
     * ore_gneiss integer
     */
    ore_gneiss?: number;
    /**
     * ore_harvestable_cloud integer
     */
    ore_harvestable_cloud?: number;
    /**
     * ore_hedbergite integer
     */
    ore_hedbergite?: number;
    /**
     * ore_hemorphite integer
     */
    ore_hemorphite?: number;
    /**
     * ore_ice integer
     */
    ore_ice?: number;
    /**
     * ore_jaspet integer
     */
    ore_jaspet?: number;
    /**
     * ore_kernite integer
     */
    ore_kernite?: number;
    /**
     * ore_mercoxit integer
     */
    ore_mercoxit?: number;
    /**
     * ore_omber integer
     */
    ore_omber?: number;
    /**
     * ore_plagioclase integer
     */
    ore_plagioclase?: number;
    /**
     * ore_pyroxeres integer
     */
    ore_pyroxeres?: number;
    /**
     * ore_scordite integer
     */
    ore_scordite?: number;
    /**
     * ore_spodumain integer
     */
    ore_spodumain?: number;
    /**
     * ore_veldspar integer
     */
    ore_veldspar?: number;
}
