/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * yesterday object
 */
export interface GetFwLeaderboardsCharactersYesterdayYesterday1 { 
    /**
     * Amount of victory points
     */
    amount?: number;
    /**
     * character_id integer
     */
    character_id?: number;
}
