/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetStatusOk { 
    /**
     * Current online player count
     */
    players: number;
    /**
     * Running version as string
     */
    server_version: string;
    /**
     * Server start timestamp
     */
    start_time: Date;
    /**
     * If the server is in VIP mode
     */
    vip?: boolean;
}
