/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseCategoriesCategoryIdOk { 
    /**
     * category_id integer
     */
    category_id: number;
    /**
     * groups array
     */
    groups: Array<number>;
    /**
     * name string
     */
    name: string;
    /**
     * published boolean
     */
    published: boolean;
}
