/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostCorporationsCorporationIdAssetsLocationsPosition } from './postCorporationsCorporationIdAssetsLocationsPosition';


/**
 * 200 ok object
 */
export interface PostCorporationsCorporationIdAssetsLocations200Ok { 
    /**
     * item_id integer
     */
    item_id: number;
    position: PostCorporationsCorporationIdAssetsLocationsPosition;
}
