/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface PostCharactersAffiliation200Ok { 
    /**
     * The character's alliance ID, if their corporation is in an alliance
     */
    alliance_id?: number;
    /**
     * The character's ID
     */
    character_id: number;
    /**
     * The character's corporation ID
     */
    corporation_id: number;
    /**
     * The character's faction ID, if their corporation is in a faction
     */
    faction_id?: number;
}
