/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BadRequest } from '../model/badRequest';
import { DeleteFleetsFleetIdMembersMemberIdNotFound } from '../model/deleteFleetsFleetIdMembersMemberIdNotFound';
import { DeleteFleetsFleetIdSquadsSquadIdNotFound } from '../model/deleteFleetsFleetIdSquadsSquadIdNotFound';
import { DeleteFleetsFleetIdWingsWingIdNotFound } from '../model/deleteFleetsFleetIdWingsWingIdNotFound';
import { ErrorLimited } from '../model/errorLimited';
import { Forbidden } from '../model/forbidden';
import { GatewayTimeout } from '../model/gatewayTimeout';
import { GetCharactersCharacterIdFleetNotFound } from '../model/getCharactersCharacterIdFleetNotFound';
import { GetCharactersCharacterIdFleetOk } from '../model/getCharactersCharacterIdFleetOk';
import { GetFleetsFleetIdMembersNotFound } from '../model/getFleetsFleetIdMembersNotFound';
import { GetFleetsFleetIdNotFound } from '../model/getFleetsFleetIdNotFound';
import { GetFleetsFleetIdOk } from '../model/getFleetsFleetIdOk';
import { GetFleetsFleetIdWingsNotFound } from '../model/getFleetsFleetIdWingsNotFound';
import { InternalServerError } from '../model/internalServerError';
import { PostFleetsFleetIdMembersInvitation } from '../model/postFleetsFleetIdMembersInvitation';
import { PostFleetsFleetIdMembersNotFound } from '../model/postFleetsFleetIdMembersNotFound';
import { PostFleetsFleetIdMembersUnprocessableEntity } from '../model/postFleetsFleetIdMembersUnprocessableEntity';
import { PostFleetsFleetIdWingsCreated } from '../model/postFleetsFleetIdWingsCreated';
import { PostFleetsFleetIdWingsNotFound } from '../model/postFleetsFleetIdWingsNotFound';
import { PostFleetsFleetIdWingsWingIdSquadsCreated } from '../model/postFleetsFleetIdWingsWingIdSquadsCreated';
import { PostFleetsFleetIdWingsWingIdSquadsNotFound } from '../model/postFleetsFleetIdWingsWingIdSquadsNotFound';
import { PutFleetsFleetIdMembersMemberIdMovement } from '../model/putFleetsFleetIdMembersMemberIdMovement';
import { PutFleetsFleetIdMembersMemberIdNotFound } from '../model/putFleetsFleetIdMembersMemberIdNotFound';
import { PutFleetsFleetIdMembersMemberIdUnprocessableEntity } from '../model/putFleetsFleetIdMembersMemberIdUnprocessableEntity';
import { PutFleetsFleetIdNewSettings } from '../model/putFleetsFleetIdNewSettings';
import { PutFleetsFleetIdNotFound } from '../model/putFleetsFleetIdNotFound';
import { PutFleetsFleetIdSquadsSquadIdNaming } from '../model/putFleetsFleetIdSquadsSquadIdNaming';
import { PutFleetsFleetIdSquadsSquadIdNotFound } from '../model/putFleetsFleetIdSquadsSquadIdNotFound';
import { PutFleetsFleetIdWingsWingIdNaming } from '../model/putFleetsFleetIdWingsWingIdNaming';
import { PutFleetsFleetIdWingsWingIdNotFound } from '../model/putFleetsFleetIdWingsWingIdNotFound';
import { ServiceUnavailable } from '../model/serviceUnavailable';
import { Unauthorized } from '../model/unauthorized';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FleetsService {

    protected basePath = 'https://esi.evetech.net/latest';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Kick fleet member
     * Kick a fleet member  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param member_id The character ID of a member in this fleet
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling deleteFleetsFleetIdMembersMemberId.');
        }

        if (member_id === null || member_id === undefined) {
            throw new Error('Required parameter member_id was null or undefined when calling deleteFleetsFleetIdMembersMemberId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/members/${encodeURIComponent(String(member_id))}/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete fleet squad
     * Delete a fleet squad, only empty squads can be deleted  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param squad_id The squad to delete
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFleetsFleetIdSquadsSquadId(fleet_id: number, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFleetsFleetIdSquadsSquadId(fleet_id: number, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFleetsFleetIdSquadsSquadId(fleet_id: number, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFleetsFleetIdSquadsSquadId(fleet_id: number, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling deleteFleetsFleetIdSquadsSquadId.');
        }

        if (squad_id === null || squad_id === undefined) {
            throw new Error('Required parameter squad_id was null or undefined when calling deleteFleetsFleetIdSquadsSquadId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/squads/${encodeURIComponent(String(squad_id))}/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete fleet wing
     * Delete a fleet wing, only empty wings can be deleted. The wing may contain squads, but the squads must be empty  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param wing_id The wing to delete
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFleetsFleetIdWingsWingId(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFleetsFleetIdWingsWingId(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFleetsFleetIdWingsWingId(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFleetsFleetIdWingsWingId(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling deleteFleetsFleetIdWingsWingId.');
        }

        if (wing_id === null || wing_id === undefined) {
            throw new Error('Required parameter wing_id was null or undefined when calling deleteFleetsFleetIdWingsWingId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/wings/${encodeURIComponent(String(wing_id))}/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get character fleet info
     * Return the fleet ID the character is in, if any.  --- Alternate route: &#x60;/dev/characters/{character_id}/fleet/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fleet/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/fleet/&#x60;  --- This route is cached for up to 60 seconds
     * @param character_id An EVE character ID
     * @param datasource The server name you would like data from
     * @param If_None_Match ETag from a previous request. A 304 will be returned if this matches the current ETag
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCharactersCharacterIdFleet(character_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'body', reportProgress?: boolean): Observable<GetCharactersCharacterIdFleetOk>;
    public getCharactersCharacterIdFleet(character_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCharactersCharacterIdFleetOk>>;
    public getCharactersCharacterIdFleet(character_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCharactersCharacterIdFleetOk>>;
    public getCharactersCharacterIdFleet(character_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (character_id === null || character_id === undefined) {
            throw new Error('Required parameter character_id was null or undefined when calling getCharactersCharacterIdFleet.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;
        if (If_None_Match !== undefined && If_None_Match !== null) {
            headers = headers.set('If-None-Match', String(If_None_Match));
        }

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<GetCharactersCharacterIdFleetOk>(`${this.basePath}/characters/${encodeURIComponent(String(character_id))}/fleet/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get fleet information
     * Return details about a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60;  --- This route is cached for up to 5 seconds
     * @param fleet_id ID for a fleet
     * @param datasource The server name you would like data from
     * @param If_None_Match ETag from a previous request. A 304 will be returned if this matches the current ETag
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsFleetId(fleet_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'body', reportProgress?: boolean): Observable<GetFleetsFleetIdOk>;
    public getFleetsFleetId(fleet_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetFleetsFleetIdOk>>;
    public getFleetsFleetId(fleet_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetFleetsFleetIdOk>>;
    public getFleetsFleetId(fleet_id: number, datasource?: 'tranquility' | 'singularity', If_None_Match?: string, token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling getFleetsFleetId.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;
        if (If_None_Match !== undefined && If_None_Match !== null) {
            headers = headers.set('If-None-Match', String(If_None_Match));
        }

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<GetFleetsFleetIdOk>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get fleet members
     * Return information about fleet members  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60;  --- This route is cached for up to 5 seconds
     * @param fleet_id ID for a fleet
     * @param Accept_Language Language to use in the response
     * @param datasource The server name you would like data from
     * @param If_None_Match ETag from a previous request. A 304 will be returned if this matches the current ETag
     * @param language Language to use in the response, takes precedence over Accept-Language
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsFleetIdMembers(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<any>>;
    public getFleetsFleetIdMembers(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<any>>>;
    public getFleetsFleetIdMembers(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<any>>>;
    public getFleetsFleetIdMembers(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling getFleetsFleetIdMembers.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (language !== undefined && language !== null) {
            queryParameters = queryParameters.set('language', <any>language);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;
        if (Accept_Language !== undefined && Accept_Language !== null) {
            headers = headers.set('Accept-Language', String(Accept_Language));
        }
        if (If_None_Match !== undefined && If_None_Match !== null) {
            headers = headers.set('If-None-Match', String(If_None_Match));
        }

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<any>>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/members/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get fleet wings
     * Return information about wings in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60;  --- This route is cached for up to 5 seconds
     * @param fleet_id ID for a fleet
     * @param Accept_Language Language to use in the response
     * @param datasource The server name you would like data from
     * @param If_None_Match ETag from a previous request. A 304 will be returned if this matches the current ETag
     * @param language Language to use in the response, takes precedence over Accept-Language
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleetsFleetIdWings(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<any>>;
    public getFleetsFleetIdWings(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<any>>>;
    public getFleetsFleetIdWings(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<any>>>;
    public getFleetsFleetIdWings(fleet_id: number, Accept_Language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', datasource?: 'tranquility' | 'singularity', If_None_Match?: string, language?: 'de' | 'en-us' | 'fr' | 'ja' | 'ru' | 'zh', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling getFleetsFleetIdWings.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (language !== undefined && language !== null) {
            queryParameters = queryParameters.set('language', <any>language);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;
        if (Accept_Language !== undefined && Accept_Language !== null) {
            headers = headers.set('Accept-Language', String(Accept_Language));
        }
        if (If_None_Match !== undefined && If_None_Match !== null) {
            headers = headers.set('If-None-Match', String(If_None_Match));
        }

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<any>>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/wings/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create fleet invitation
     * Invite a character into the fleet. If a character has a CSPA charge set it is not possible to invite them to the fleet using ESI  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60; 
     * @param fleet_id ID for a fleet
     * @param invitation Details of the invitation
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFleetsFleetIdMembers(fleet_id: number, invitation: PostFleetsFleetIdMembersInvitation, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postFleetsFleetIdMembers(fleet_id: number, invitation: PostFleetsFleetIdMembersInvitation, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postFleetsFleetIdMembers(fleet_id: number, invitation: PostFleetsFleetIdMembersInvitation, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postFleetsFleetIdMembers(fleet_id: number, invitation: PostFleetsFleetIdMembersInvitation, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling postFleetsFleetIdMembers.');
        }

        if (invitation === null || invitation === undefined) {
            throw new Error('Required parameter invitation was null or undefined when calling postFleetsFleetIdMembers.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/members/`,
            invitation,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create fleet wing
     * Create a new wing in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60; 
     * @param fleet_id ID for a fleet
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFleetsFleetIdWings(fleet_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<PostFleetsFleetIdWingsCreated>;
    public postFleetsFleetIdWings(fleet_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PostFleetsFleetIdWingsCreated>>;
    public postFleetsFleetIdWings(fleet_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PostFleetsFleetIdWingsCreated>>;
    public postFleetsFleetIdWings(fleet_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling postFleetsFleetIdWings.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<PostFleetsFleetIdWingsCreated>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/wings/`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create fleet squad
     * Create a new squad in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60; 
     * @param fleet_id ID for a fleet
     * @param wing_id The wing_id to create squad in
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFleetsFleetIdWingsWingIdSquads(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<PostFleetsFleetIdWingsWingIdSquadsCreated>;
    public postFleetsFleetIdWingsWingIdSquads(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PostFleetsFleetIdWingsWingIdSquadsCreated>>;
    public postFleetsFleetIdWingsWingIdSquads(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PostFleetsFleetIdWingsWingIdSquadsCreated>>;
    public postFleetsFleetIdWingsWingIdSquads(fleet_id: number, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling postFleetsFleetIdWingsWingIdSquads.');
        }

        if (wing_id === null || wing_id === undefined) {
            throw new Error('Required parameter wing_id was null or undefined when calling postFleetsFleetIdWingsWingIdSquads.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<PostFleetsFleetIdWingsWingIdSquadsCreated>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/wings/${encodeURIComponent(String(wing_id))}/squads/`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update fleet
     * Update settings about a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param new_settings What to update for this fleet
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFleetsFleetId(fleet_id: number, new_settings: PutFleetsFleetIdNewSettings, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putFleetsFleetId(fleet_id: number, new_settings: PutFleetsFleetIdNewSettings, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putFleetsFleetId(fleet_id: number, new_settings: PutFleetsFleetIdNewSettings, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putFleetsFleetId(fleet_id: number, new_settings: PutFleetsFleetIdNewSettings, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling putFleetsFleetId.');
        }

        if (new_settings === null || new_settings === undefined) {
            throw new Error('Required parameter new_settings was null or undefined when calling putFleetsFleetId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/`,
            new_settings,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Move fleet member
     * Move a fleet member around  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param member_id The character ID of a member in this fleet
     * @param movement Details of the invitation
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, movement: PutFleetsFleetIdMembersMemberIdMovement, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, movement: PutFleetsFleetIdMembersMemberIdMovement, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, movement: PutFleetsFleetIdMembersMemberIdMovement, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putFleetsFleetIdMembersMemberId(fleet_id: number, member_id: number, movement: PutFleetsFleetIdMembersMemberIdMovement, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling putFleetsFleetIdMembersMemberId.');
        }

        if (member_id === null || member_id === undefined) {
            throw new Error('Required parameter member_id was null or undefined when calling putFleetsFleetIdMembersMemberId.');
        }

        if (movement === null || movement === undefined) {
            throw new Error('Required parameter movement was null or undefined when calling putFleetsFleetIdMembersMemberId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/members/${encodeURIComponent(String(member_id))}/`,
            movement,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Rename fleet squad
     * Rename a fleet squad  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param naming New name of the squad
     * @param squad_id The squad to rename
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFleetsFleetIdSquadsSquadId(fleet_id: number, naming: PutFleetsFleetIdSquadsSquadIdNaming, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putFleetsFleetIdSquadsSquadId(fleet_id: number, naming: PutFleetsFleetIdSquadsSquadIdNaming, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putFleetsFleetIdSquadsSquadId(fleet_id: number, naming: PutFleetsFleetIdSquadsSquadIdNaming, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putFleetsFleetIdSquadsSquadId(fleet_id: number, naming: PutFleetsFleetIdSquadsSquadIdNaming, squad_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling putFleetsFleetIdSquadsSquadId.');
        }

        if (naming === null || naming === undefined) {
            throw new Error('Required parameter naming was null or undefined when calling putFleetsFleetIdSquadsSquadId.');
        }

        if (squad_id === null || squad_id === undefined) {
            throw new Error('Required parameter squad_id was null or undefined when calling putFleetsFleetIdSquadsSquadId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/squads/${encodeURIComponent(String(squad_id))}/`,
            naming,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Rename fleet wing
     * Rename a fleet wing  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     * @param fleet_id ID for a fleet
     * @param naming New name of the wing
     * @param wing_id The wing to rename
     * @param datasource The server name you would like data from
     * @param token Access token to use if unable to set a header
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFleetsFleetIdWingsWingId(fleet_id: number, naming: PutFleetsFleetIdWingsWingIdNaming, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putFleetsFleetIdWingsWingId(fleet_id: number, naming: PutFleetsFleetIdWingsWingIdNaming, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putFleetsFleetIdWingsWingId(fleet_id: number, naming: PutFleetsFleetIdWingsWingIdNaming, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putFleetsFleetIdWingsWingId(fleet_id: number, naming: PutFleetsFleetIdWingsWingIdNaming, wing_id: number, datasource?: 'tranquility' | 'singularity', token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fleet_id === null || fleet_id === undefined) {
            throw new Error('Required parameter fleet_id was null or undefined when calling putFleetsFleetIdWingsWingId.');
        }

        if (naming === null || naming === undefined) {
            throw new Error('Required parameter naming was null or undefined when calling putFleetsFleetIdWingsWingId.');
        }

        if (wing_id === null || wing_id === undefined) {
            throw new Error('Required parameter wing_id was null or undefined when calling putFleetsFleetIdWingsWingId.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (datasource !== undefined && datasource !== null) {
            queryParameters = queryParameters.set('datasource', <any>datasource);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // authentication (evesso) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/fleets/${encodeURIComponent(String(fleet_id))}/wings/${encodeURIComponent(String(wing_id))}/`,
            naming,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
